server:
  port: 314
  servlet:
    context-path: /tiktok
spring:
  main:
    allow-circular-references: true
    lazy-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/tiktok?serverTimezone=GMT%2B8
    username: root
    password: 307314
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  #ftdjymtxojmpcihc
  #mingdongiloveu2@qq.com
  #========================邮件
  mail:
    code-validation: 5
    host: smtp.qq.com
    username: mingdongiloveu2@qq.com
    password: "ftdjymtxojmpcihc"
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
#mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    mapper-locations: classpath:com/lartimes/tiktok/mapper/*.xml
jwt:
  config:
    expire: 86400000
    secret: ftdjymtxojmpcihc

logging:
  config: classpath:log4j2.xml
  level:
    root: info
    jakarta.activation: info
    org.apache.catalina: info
    org.apache.commons.beanutils.converters: info
    org.apache.coyote.http11.Http11Processor: info
    org.apache.http: info
    org.apache.tomcat: info
    org.springframework: info

qiniu:
  kodo:
    accessKey: ${QINIU_KODO_ACCESS:11yuYvkI--0p-gouHsUK4pW_KhO0V4UtKgIBabzt}
    secretKey: ${QINIU_KODO_SECRET:NC50ziZ_cHfb3mYG5ToWSqUCe8CtZEFm0T3TBFgb}
    bucket: ${QINIU_KODO_BUCKET:test-demo222}
    fops: avthumb/mp4
    mediaType: video/*
    imageType: image/*
    cname: http://spz6m6sd3.hb-bkt.clouddn.com
    videoUrl: http://ai.qiniuapi.com/v3/video/censor
    imageUrl: http://ai.qiniuapi.com/v3/image/censor
