server:
  port: 314
  servlet:
    context-path: /tiktok
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${DATASOURCE_HOST:127.0.0.1:3306}/${DATASOURCE_NAME:lucky-journey}?serverTimezone=GMT%2B8
    username: ${DATASOURCE_USER:root}
    password: ${DATASOURCE_PASSWORD:307314}

  data:
    redis:
      port: 6379
      host: 127.0.0.1
#ftdjymtxojmpcihc
#mingdongiloveu2@qq.com
#========================邮件
  mail:
    host: smtp.qq.com
    username: mingdongiloveu2@qq.com
    password: "ftdjymtxojmpcihc"
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
